# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_method <- function(data, boot_samples, method, replace = TRUE) {
    .Call(`_CullenFreyX_bootstrap_method`, data, boot_samples, method, replace)
}

